### ISSUE TITLE
Port gmod_tool_auto

### ISSUE THREAD

**Issue by ninjrdevelop** [Nebual/sandbox-plus#52]
> I do also want to port over gmod_tool_auto (which I used to always have bound to mouse3?) that toggles between:
> 
> <tool used to make the ent you're looking at>
> physgun
> constraint tool
> I think for plain props it did physgun, gravgun, constraint.

- @Nebual, in [!49](https://github.com/Nebual/sandbox-plus/pull/49)

**Comment by ninjrdevelop** [comment]
`<tool used to make the ent you're looking at>` would be interesting. I wonder if entities need to store the name of the tool selection convar that creates them?

**Comment by Nebual** [comment]
I originally [made this as an addon ](https://github.com/Nebual/sbox_tool_auto) (though since addons are dead currently, lets just bake it into the gamemode directly)

It mostly worked by assuming that `ent.ClassName = 'ent_wirebutton'` would work with a 'tool_wirebutton', though it allowed Entitys to define an optional tool (or list of) to override that assumption.

So far in this Component-based system, my Lamp has a `LampComponent`, and the balloon and wheel are just props with "balloon" or "wheel" added as Tags, so I'm not quite sure what we can use there. I am unrelatedly about to add
```
	protected override bool IsMatchingEntity( GameObject go )
	{
		return go.Tags.Has( "balloon" );
	}
```
to most tools (to know if we should Update its settings or Spawn a new one), we could plausibly iterate over instances of all tools matching them against <gameobject you're looking at> and see if any match.

**Comment by Nebual** [comment]
Added in b948f33b8904ae5e5fb96e7f0132985c6dd8e329 - it just iterates through all the components in the trace.GameObject looking for ones with matching tools, works great for all the tools currently in.
